config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => {:registrations => 'registrations', :omniauth_callbacks => 'callbacks'}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to:  'devise/registrations#new'
  end

  root to: 'application#welcome'
  
  resources :userscourses, only: [:index, :show, :destroy] do 
    resources :projects, only: [:new,:create, :show]
  end

  resources :projects, only: [:index]

  post '/categories/:category_id/courses/:id', to: "userscourses#create", as: "new_usercourse"


  resources :categories do
    resources :courses  
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :courses
    has_many :userscourses, through: :courses
    
    validates :name, presence: true
    validates :name, uniqueness: true

    accepts_nested_attributes_for :courses, reject_if: :all_blank
    
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to :category
    has_many :userscourses
    has_many :projects, through: :userscourses

    validates :name, uniqueness: true
    validates :name, :description, presence: true

    accepts_nested_attributes_for :category

    def self.search(search)
        if search
            where(["name LIKE ?", "%#{search}%"])
        end
    end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :userscourse
  belongs_to :user

  validates :name, presence: true

  scope :by_date, -> { order('created_at DESC, id DESC') }

  accepts_nested_attributes_for :userscourse, reject_if: :all_blank
end

app/models/user.rb
class User < ApplicationRecord
  has_many :userscourses
  has_many :projects, through: :userscourses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider 
      user.username = auth.info.name
      user.uid = auth.uid 
      user.email = auth.info.email 
      user.password = Devise.friendly_token[0,20]
    end
  end
  
end

app/models/userscourse.rb
class Userscourse < ApplicationRecord
    belongs_to :user
    belongs_to :course
    has_many :projects

    accepts_nested_attributes_for :projects, reject_if: :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def welcome
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :authenticate_user!
before_action :set_category, only: [ :show, :edit, :update, :destroy]

    def index
        if params[:search]
            @course = Course.search(params[:search])
        end
        @category = Category.all
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(name: params[:category][:name])
        if @category.valid?
            @category.save
            redirect_to @category
        else 
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        @category.update(name: params[:category][:name])
        if @category.valid?
            redirect_to category_path(@category)
        else
            render :edit
        end
    end

    def destroy
        @category.destroy
        redirect_to categories_path
    end

    private

    def set_category
        @category = Category.find_by(id: params[:id])
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
before_action :authenticate_user!
before_action :set_course, only: [:create, :show, :edit, :update, :destroy]
before_action :set_category, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  def index
      @course = Course.all
      # @search = Course.where(["name LIKE ?", "%#{params[:search]}%"])
  end

  def new
    if params[:category_id]
     set_category
      @course = @category.courses.build
    else
      redirect_to categories_path
    end
  end

  def create
      @course = Course.new(course_params)
      if @course.valid?
        @course.save
        redirect_to category_course_path(@category, @course)
      else 
        render :new
      end
  end

  def show
    if params[:category_id]
      set_category
      if @category.nil?
        redirect_to categories_path
      else
        @course = @category.courses.find_by(id: params[:id])
        if @course.nil?
          redirect_to categories_path
        end
      end 
    else
      # @course = Course.find(params[:id])
      # set_course
    end
  end

  def edit
    if params[:category_id]
      set_category
        if @category.nil?
          redirect_to categories_path
        else
          @course = @category.courses.find_by(id: params[:id])
          if @course.nil?
            redirect_to category_courses_path(@category)
          end 
        end
    else
      # set_course
    end 
  end

  def update
    @course = @category.courses.find_by(id: params[:id])
    @course.update(course_params)
    if @course.save
      redirect_to category_course_path
    else  
      render :edit
    end
  end

  def destroy
    Course.find(params[:id]).destroy
    redirect_to category_courses_path
  end

  private

  def set_category
    @category = Category.find_by(id: params[:category_id])
  end

  def set_course
    @course = Course.find_by(id: params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :description, :category_id)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [ :show, :edit, :update, :destroy]
  before_action :set_userscourse, only: [ :new, :create]

  def index
    @project = current_user.projects.by_date
  end

  def new
    if params[:userscourse_id]
      @project = @userscourse.projects.build
      if @userscourse.nil?
        redirect_to userscourses_path
      else
        @project = @userscourse.projects.build
      end      
    end
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.valid?
      @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @project.update(project_params)
    if @project
      redirect_to project_path(@project)
    else 
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_userscourse
    @userscourse = current_user.userscourses.find_by(id: params[:userscourse_id])
  end

  def set_project
    @project = current_user.projects.find_by(id: params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :user_id, :userscourse_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def signup_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/controllers/userscourses_controller.rb
class UserscoursesController < ApplicationController
  before_action :authenticate_user!

  def index
      @userscourses = current_user.userscourses
  end

  def create
    @userscourses = current_user.userscourses.build(:user_id => current_user.id, :course_id => params[:id])
    if @userscourses.valid?
      @userscourses.save
      redirect_to  userscourses_path 
    else 
      flash.alert = "Failed to join course."
      redirect_to userscourses_path 
    end
  end

  def show
    @userscourses = Userscourse.find_by(id: params[:id])
  end

  def destroy
    Userscourse.find_by(id: params[:id]).destroy
    redirect_to userscourses_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/userscourses_helper.rb
module UserscoursesHelper
end

app/views/application/welcome.html.erb
<h1>Welcome to the School Domain</h1>

<% if user_signed_in?%>

    <% if current_user.admin?%>
        <h3><%= link_to "View Categories and Courses", categories_path%></h3>
        <br>
        <h3><%= link_to "Add Categories or Courses", new_category_path%></h3>
    <%else%>

        <br>
        <h3><%= link_to "View my courses",  userscourses_path%></h3>
        <br>
        <h3><%= link_to "Browse Categories", categories_path%></h3>
        <br>
        <h3><%= link_to "View Projects and Assignments",  projects_path%></h3>

    <%end%>

<%else%>

    <h3>Please Log in or Sign up to continue.</h3>

<%end%>

app/views/categories/_form.html.erb
<% if current_user.admin?%>
    <%= form_for(@category) do |f| %> 

        <% if @category.errors.any? %>
        <div id="error_explanation">
            <h2>There were some errors:</h2>
            <ul>
            <% @category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
        </div>
        <% end %>

        <h1>New Category</h1> <%= f.label :name%><br>
        <%= f.text_field :name%>
        <br>
        <%= f.submit%>
    <%end%>
<%end%>

app/views/categories/edit.html.erb
<%= render 'form'%>

app/views/categories/index.html.erb
<% if current_user%>
    
    <p>Search Courses:</p>
            <%= form_tag(categories_path, method: :get) do%>
                <%= text_field_tag(:search, params[:search])%>
                <%= submit_tag "Search"%>
            <%end%>
            <br>
    <% if @course%>
                <% @course.each do |course| %>
                <ul>
                    <br>
                    <li><%= link_to course.name, category_course_path(course.category_id, course.id) %></li><br>
                </ul>
                <br>
            <%end%>
    <%end%>

    <h1>Categories:</h1>

    <% @category.each do |category| %>
        <br>
        <li><%= link_to category.name, category_path(category) %></li>
        <br>
    <%end%>

<%end%>

app/views/categories/new.html.erb
<%= render 'form'%>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name%></h1>

<h3>Courses:</h3>
<br>
<% @category.courses.each do |course|%>
    <p><%= link_to course.name, category_course_path(@category, course)%></p><br><br>
<%end%>

<% if current_user.admin?%>
    <%= link_to "Add Courses", new_category_course_path(@category.id) %><br><br>
    <%= link_to "Edit Category", edit_category_path %><br><br>

    <%= link_to "Delete Category",  @category, method: :delete%>
<%end%>

app/views/courses/_form.html.erb
<%if current_user.admin?%>
    <% flash.each do |type, msg| %>
        <div>
            <%= msg %>
        </div>
    <% end %>

    <%= form_for [@category, @course] do |f| %>

    <% if @course.errors.any? %>
        <div id="error_explanation">
            <h2>There were some errors:</h2>
            <ul>
            <% @course.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    
        <%= f.label :name%>
        <%= f.text_field :name%>
        <%= f.hidden_field :category_id %>
        <%= f.label :description%>
        <%= f.text_field :description%>

        <%= f.submit%>
    <%end%>
<%end%>

app/views/courses/edit.html.erb
 <%= render 'form' %>

app/views/courses/index.html.erb
<h1>Courses: </h1>

    <% @course.each do |course|%>
            <li><%= link_to course.name, category_course_path(@category, course)%></li>
        <%end%>
    <br>
    <br>

    <%= link_to "Join a new course", categories_path%>

app/views/courses/new.html.erb
 <%= render 'form' %>

app/views/courses/show.html.erb
<% if current_user.admin?%>
    <h1>Class name: </h1>
        <br><p><%= @course.name%></p>
        <br>
        <br>
        <h1>Class description:</h1><br>
        <p><%= @course.description%></p><br>
        <%= link_to "Edit Course", edit_category_course_path%>
        <%= link_to "Delete Course", [@category,@course], :method => :delete%><br>
<%else%>
    <% flash.each do |type, msg| %>
        <div>
            <%= msg %>
        </div>
    <% end %>
    <h1>Class name: </h1>
        <br><%= @course.name%>
        <br>
        <br>
        <h1>Class description:</h1><br>
        <%= @course.description%>
    <%= button_to "Join this class", new_usercourse_path%>
    
<%end%>

app/views/layouts/_nav.html.erb
<header>
    <nav>
        <ul>
            <li><%= link_to "Home", root_path%></li>
            <% if !user_signed_in?%>
                <li ><%= link_to "Sign Up", new_user_registration_path%></li>
                <li><%= link_to "Log In", new_user_session_path %></li>
            <%else%>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
                <li><%= current_user.email%></li>
            <%end%>
        </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Class Domain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      
    <%= render 'layouts/nav'%>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<% if current_user%>
    <%= form_for [@userscourse, @project] do |f|%>

      <% if @project.errors.any? %>
    <div id="error_explanation">
        <h2>There were some errors:</h2>
        <ul>
        <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

        Project <%= f.label :name%>
        <%= f.text_field :name%>
        <br>
        <%= f.hidden_field :user_id, value: current_user.id%>
        <%= f.hidden_field :userscourse_id%>
        <br>
        <%= f.submit%>
    <%end%>
<%end%>

app/views/projects/edit.html.erb
<%= render 'form'%>

app/views/projects/index.html.erb
<h1>Projects and Assignments: </h1>
<ol>
    <% current_user.projects.each do |project| %>
            <li><%= project.name%></li>
            <br>
            <br>
    <%end%>
</ol>

app/views/projects/new.html.erb
<%= render 'form'%>

app/views/userscourses/index.html.erb
<%if current_user%>
    <h1>My courses:</h1>
    <% @userscourses.each do |uc|%>
    <br>
        <%= link_to uc.course.name, userscourse_path(uc) %><br>
    <%end%>
    <br>
    <br>
    <%= link_to "Add new course",  categories_path%>
<%end%>

app/views/userscourses/show.html.erb
<% if current_user%>
<h3>Class Name:</h3>

    <%= @userscourses.course.name%>
    <br>
    <br>
    <h3>Class Info: </h3>

    <%= @userscourses.course.description%>
    <br>
    <br>

    <%= link_to "Create Project and/or Assignment", new_userscourse_project_path(@userscourses)%>
    <br>
    <br>
    <%= link_to "Drop Course", @userscourses, method: :delete%>

<%end%>